# Site settings
title: Code Hub
email: andrzej@3scale.net
description: "3scale Code Hub snippet library"
baseurl: ""
url: "http://codehub.3scale.net"
github_username:  jerzyn

# Build settings
markdown: kramdown
permalink: pretty
include: search.json

highlighter: pygments
gems: ['jekyll-lunr-js-search']

lunr_search:
  excludes: [index.html, about.md]